### ISSUE TITLE
Limit on the number of requests and threads

### ISSUE THREAD

**Issue by jidckii** [vedhavyas/sitemap-generator#4]
Hi, thanks for the project.  
Is there an opportunity to add a limit on the number of requests and threads?  
My site on node.js does not stand up and falls, after starting the scan.  

Also scan relative to uri.  
For example, locale:  
```
/en-us
/de-de
/ru-ru
```

**Comment by vedhavyas** [comment]
Hey @jidckii 
Thanks for using the project. I will take a look at this weekend.

**Comment by jidckii** [comment]
Thank you, not need.
I created my app ))
https://github.com/jidckii/sicra
